import Layout from "@/components/Layout";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import imageProfile from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>HTA | Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-black w-full min-h-screen dark:text-light ">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={imageProfile}
                alt="TuanAnh"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center  pb-[80px]">
              <AnimatedText
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl dark:text-light"
                text="I am a creative Front-end Developer "
              />
              <p className="my-4 text-base font-medium dark:text-light md:text-sm sm:text-xs">
                I develope websites that gets you real results. With 1+ years of
                experience, I specialize in building online solutions for the
                many domains: Game Blockchain, ERP , Payment Gateway, NFT
                Marketplace
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-black dark:bg-white text-white dark:text-dark
                  p-2.5 px-6 rounded-lg text-lg font-semibold 
                  hover:bg-white hover:text-black 
                  border-2 border-solid border-transparent hover:border-black
                  hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light
                  md:p-2 md:px-4 md:text-base
                  "
                  download={true}
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="/mailto:abcd@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-black underline dark:text-light
                  md:text-light md:text-base
                  "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="UTH" className="w-full h-auto " />
        </div>
      </main>
    </>
  );
}
